### ISSUE TITLE
image offset on the right the more images you have

### ISSUE THREAD

**Issue by Myystigri** [lucaspulliese/vue-cool-lightbox#77]
It's not that obvious on the documentation example because there's only 3 images but basically the problem is that based on the index of the image in the slider, the image will be shifted slightly on the right. 
With 3 images it's subtle enough to not care, but the more images you have, the more obvious it is.
Also it only happens based on the position of the image you clicked on to open the slider (if you click on the first image then slide through them to the last one, no offset, but if you open the last image it will be shifted on the right)

https://user-images.githubusercontent.com/16547785/106440397-1caf4100-6479-11eb-8e93-3e2509404e87.mp4
You can see it in this example by looking at the space difference on the right of the image based on which image i opened the slider with

It's also to note that the bug doesn't seem to appear on big sur chrome and safari but it does happen on the last version of chrome in windows 10

**Comment by Subilan** [comment]
same here, lol

**Comment by Myystigri** [comment]
Fixed with 2.7.1

**Comment by Subilan** [comment]
Nope, the problem is still to me😥(no matter "bottom" gallery or "right" gallery). I fixed it by using fade effect which does not depend on swiper things.

**Comment by ajordaan** [comment]
Have the same issue except the Images are offset to the left. Seems like only the swipe effect is affected by this and only on mobile screen sizes. No issue when using the fade effect.

Difference in offset between the 3rd and 12th image in the array:

![LIghtBox1](https://user-images.githubusercontent.com/8866267/123117650-3b22d280-d442-11eb-8880-df2d96e5a005.png)
![LIghtBox2](https://user-images.githubusercontent.com/8866267/123117675-40801d00-d442-11eb-9679-86c02f59214f.png)

**Comment by OleksiiBrylin** [comment]
effect="fade" helped to skip the issue for me
